#!/usr/bin/zsh

start_unique_process() {
    n_processes=$(ps -ef | grep "$1" | grep -v "grep" | wc -l)
    if [[ "$n_processes" != "1" ]]; then
        killall "$1" &> /dev/null
        $(eval "$1 &") &> /dev/null
    fi
}

PATH="$PATH:$HOME/.bin:$HOME/.local/bin"
DEVELOP_HOME="$HOME/Develop"
UTILS_HOME="$HOME/.config/utils"

# BEGIN APP DIRECTORIES
GIT_HOME="/bin/git"
LS_HOME="/bin/ls"
FLUTTER_HOME="$DEVELOP_HOME/socialweb/flutter"
PYTHON_HOME=""
JAVA_HOME=""
NEOVIM_HOME="/usr/bin/nvim"
# END APP DIRECTORIES

if [[ "$OSTYPE" == "linux-gnu"* ]];then
    # BEGIN LINUX ENVIRONMENT VARIABLES
    PATH="$PATH:$HOME/go/bin"
    # END LINUX ENVIRONMENT VARIABLES

    if [[ "$PWM" == "xmonad" ]]; then
        # screen layout
        xrandr --output DVI-D-1 --primary --mode 1920x1080 --pos 1360x0 --rotate normal --output HDMI-1 --mode 1360x768 --pos 0x0 --rotate normal --output DP-1 --off

        # no screen sleep
        xset s off
        xset s 0 0
        xset -dpms

        # turn on numlock automatically
        numlockx on

        # start trayer icons
        #(start_unique_process "nm-applet" &) &> /dev/null
        #(start_unique_process "volumeicon" &) &> /dev/null
    fi

elif [[ "$OSTYPE" == "darwin"* ]]; then
    # BEGIN MAC ENVIRONMENT VARIABLES
    LS_HOME="/usr/local/opt/coreutils/libexec/gnubin/ls"
    JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-16.0.1.jdk/Contents/Home"
    PYTHON_HOME="/Library/Frameworks/Python.framework/Versions/3.9/bin"
    NEOVIM_HOME="/usr/local/bin/nvim"
    # END MAC ENVIRONMENT VARIABLES

    PATH="$PATH:$HOME/.pub-cache/bin"


elif [[ "$OSTYPE" == "win"* ]]; then
    # BEGIN WINDOWS ENVIRONMENT VARIABLES
    # END WINDOWS ENVIRONMENT VARIABLES


fi

# BEGIN COMMON PATHS
PATH="$PATH:$JAVA_HOME/bin"
PATH="$PATH:$PYTHON_HOME/bin"
PATH="$PATH:$FLUTTER_HOME/bin"
# END COMMON PATHS

typeset -U path

# BEGIN VARIABLE EXPORTS
export DEVELOP_HOME
export GIT_HOME
export LS_HOME
export FLUTTER_HOME
export JAVA_HOME
export NEOVIM_HOME
export PATH
# END VARIABLE EXPORTS
